apiVersion: portal.gloo.solo.io/v1beta1
kind: Group
metadata:
  name: users
  namespace: petstore 
spec:
  displayName: corporate users
  accessLevel:
    portals:
    - name: ecommerce-portal
      namespace: petstore
  oidcGroup:
    groupName: users # this represents the group name in the IdP (Keycloak)
