apiVersion: portal.gloo.solo.io/v1beta1
kind: Group
metadata:
  name: users
  namespace: gloo-portal 
spec:
  accessLevel:
    portals:
    - name: ecommerce-portal
      namespace: petstore
  displayName: corporate users
  oidcGroup:
    groupName: users
