apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: argocd 
  namespace: argocd
spec:
  virtualHost:
    domains:
    - argocd.mycompany.corp
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: argocd-argocd-server-80
            namespace: gloo-system
