apiVersion: portal.gloo.solo.io/v1beta1
kind: Environment
metadata:
  name: dev
  namespace: petstore
spec:
  apiProducts: # we will select our APIProduct using a selector and the 2 version of it
    - namespaces:
      - "*" 
      labels:
      - key: app
        operator: In
        values:
        - petstore
      versions:
        names:
        - v1
        - v2
      basePath: "{%version%}" # this will dynamically prefix the API with the version names
      # ------------------------ NEW -----------------------------
      usagePlans:
        - trusted
      # ----------------------------------------------------------
  # ------------------------- NEW --------------------------------
  parameters:
    usagePlans:
      trusted:
        displayName: trusted plan
        rateLimit:
          unit: MINUTE
          requestsPerUnit: 10
        authPolicy:
          oauth:
            authorizationUrl: http://18.221.19.252:8080/auth/realms/master/protocol/openid-connect/auth
            tokenUrl: http://18.221.19.252:8080/auth/realms/master/protocol/openid-connect/token
            jwtValidation:
              issuer: http://18.221.19.252:8080/auth/realms/master
              remoteJwks:
                refreshInterval: 60s
                url: http://18.221.19.252:8080/auth/realms/master/protocol/openid-connect/certs
  # ----------------------------------------------------------------
