apiVersion: portal.gloo.solo.io/v1beta1
kind: Group
metadata:
  name: users
  namespace: default 
spec:
  displayName: internal users
  accessLevel:
    portals:
    - name: ecommerce-portal
      namespace: default
  groupNames: 
    - users # this represents the group name in the IdP (Keycloak)
